  on:
    push:
      branches:[main]
    pull_request:
        branches:[main]

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Go 1.20
          uses: actions/setup-go@v2
          with:
            go-version: 1.20
        - name: Build
          run: go build -v ./...
        - name: Unit Test
          run: go test -v ./...
        - name: Lint
          run: golangci-lint run
        - name: Integeration Test
          run: "go install -v github.com/Vignesh-Rajarajan/event-bus/cmd/integration-test && ~/go/bin/integration-test"