  on:
    push:
      branches:[main]
    pull_request:
        branches:[main]

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Go 1.20
          uses: actions/setup-go@v2
          with:
            go-version: 1.20
        - name: Get etcg
          run: 'export ETCD_VER="v3.5.12" && curl -L https://github.com/etcd-io/etcd/releases/download/${ETCD_VER}/etcd-${ETCD_VER}-linux-amd64.tar.gz -o etcd-${ETCD_VER}-linux-amd64.tar.gz && tar xzvf - -C ~/go/bin/ --strip-components=1'
        - name: Build
          run: go build -v ./...
        - name: Unit Test
          run: go test -v ./...
        - name: Lint
          run: golangci-lint run
        - name: Integeration Test
          run: "go install -v github.com/Vignesh-Rajarajan/event-bus/cmd/integration-test && ~/go/bin/integration-test"